`timescale 1ns / 1ps

module tb_fun;

    // 1. Declare Signals
    reg clk;
    // Input shares
    reg a_0, a_1;
    reg b_0, b_1;
    reg c_0, c_1;
    reg d_0, d_1;
    
    // Random inputs
    reg rand_1, rand_7, rand_2, rand_5, rand_3, rand_6, rand_8, rand_4;

    // Outputs
    wire r_0;
    wire r_1;

    // Testbench Variables
    integer file_handle;
    integer scan_result;
    integer a_in, b_in, c_in, d_in, r_expected;
    integer pass_count = 0;
    integer fail_count = 0;
    
    // Variable to skip header
    reg [8*100:1] header_str; // 100 characters max

    // 2. Instantiate the DUT (Device Under Test)
    fun uut (
        .clk(clk), 
        .a_0(a_0), .a_1(a_1), 
        .b_0(b_0), .b_1(b_1), 
        .c_0(c_0), .c_1(c_1), 
        .d_0(d_0), .d_1(d_1), 
        .rand_1(rand_1), .rand_7(rand_7), .rand_2(rand_2), .rand_5(rand_5), 
        .rand_3(rand_3), .rand_6(rand_6), .rand_8(rand_8), .rand_4(rand_4), 
        .r_0(r_0), .r_1(r_1)
    );

    // 3. Clock Generation (10ns period)
    initial begin
        clk = 0;
        forever #5 clk = ~clk; 
    end

    // 4. Test Sequence
    initial begin
        // Open the CSV file generated by Python
        file_handle = $fopen("expected_outputs.csv", "r");
        if (file_handle == 0) begin
            $display("ERROR: Could not open expected_outputs.csv");
            $finish;
        end

        // Skip the header line (read it as a string and discard)
        // Adjust this if your simulator doesn't support string reading well, 
        // or just ensure the CSV has no header if this fails.
        scan_result = $fgets(header_str, file_handle); 

        $display("Starting Verification...");
        $display("Time | a | b | c | d | Exp | Act (r0^r1) | Result");
        $display("-------------------------------------------------------");

        while (!$feof(file_handle)) begin
            // Read values from CSV: a,b,c,d,r_expected
            scan_result = $fscanf(file_handle, "%d,%d,%d,%d,%d\n", a_in, b_in, c_in, d_in, r_expected);

            if (scan_result == 5) begin
                // --- SETUP SHARES ---
                // For functional verification, we set:
                // Share 0 = Input Value
                // Share 1 = 0
                // This satisfies the property: (Share0 ^ Share1) == Input
                a_0 = a_in; a_1 = 0;
                b_0 = b_in; b_1 = 0;
                c_0 = c_in; c_1 = 0;
                d_0 = d_in; d_1 = 0;

                // Randomize mask inputs to ensure logic works with noise
                rand_1 = $random; rand_2 = $random; rand_3 = $random; rand_4 = $random;
                rand_5 = $random; rand_6 = $random; rand_7 = $random; rand_8 = $random;

                // --- WAIT FOR PIPELINE ---
                // Your design has roughly 6-8 register stages deep.
                // We wait 20 cycles to ensure data propagates fully.
                repeat (20) @(posedge clk);

                // --- CHECK OUTPUT ---
                // Reconstruct the actual output: r_actual = r_0 XOR r_1
                if ((r_0 ^ r_1) === r_expected) begin
                    $display("%4t | %d | %d | %d | %d |  %d  |      %d      | PASS", 
                             $time, a_in, b_in, c_in, d_in, r_expected, (r_0 ^ r_1));
                    pass_count = pass_count + 1;
                end else begin
                    $display("%4t | %d | %d | %d | %d |  %d  |      %d      | FAIL", 
                             $time, a_in, b_in, c_in, d_in, r_expected, (r_0 ^ r_1));
                    fail_count = fail_count + 1;
                end
            end
        end

        $display("-------------------------------------------------------");
        $display("Final Result: Passed = %d, Failed = %d", pass_count, fail_count);
        $fclose(file_handle);
        $finish;
    end

endmodule